---
title: "Analysis Report"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    theme: flatly
    highlight: tango
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

## Load Libraries

```{r}
suppressPackageStartupMessages(library(here))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(MultiAssayExperiment))
suppressPackageStartupMessages(library(gt))
suppressPackageStartupMessages(library(PCAtools))


theme_set(
  theme_light() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(size = 16, face = "bold"),
        strip.text = element_text(size = 12, face = "bold"))
)
```

## Get metadata for all studies

Extract from MultiAssayexperiment files

```{r}
mae_files <- list.files(
  path = here("data"),
  pattern = "MultiAssayExperiment.rds$",
  recursive = TRUE,
  full.names = TRUE
)
names(mae_files) <- regmatches(mae_files, regexpr("PRJNA[0-9]+", mae_files))
```

## Read in all metadata

```{r}
getColdata <- function(fpath) {
  mae <- readRDS(fpath)
  colData(mae)$bases <- as.integer(colData(mae)$bases)
  coldata <- as.data.table(data.frame(colData(mae)), keep.rownames = "Run")
  coldata
}

# Extract all coldata into a single data.table
coldata <- rbindlist(lapply(mae_files, getColdata), fill = TRUE)
```

## EDA on colData

Additional numbers taken from SPORE grant update table

```{r}
se <- readRDS("~/data/projects/geo-rna-seq/results/combined/rds-files/se.rds")

# Number of samples
stats <- data.table(
  Samples = coldata[, length(unique(BioSample))],
  Experiments = coldata[, length(unique(BioProject))],
  Contrasts = nrow(colData(se)),
  Tissues = length(unique(colData(se)$tissue)),
  Diseases = length(unique(colData(se)$disease)),
  `Cell Lines` = length(unique(colData(se)$cell_line)),
  Drugs = length(unique(colData(se)$drug))
  )
  
stats <- melt(stats, variable.name = "Variable", value.name = "N")[order(N, decreasing = TRUE)]
stats
```

Create nice looking table for slides

```{r}
tab <- gt(stats) |> 
  tab_header(
    title = md("**GEO Meta-analysis Database Stats**"),
    subtitle = "Counts of unique variables"
    ) |> 
  cols_label(
    Variable = md("**Variable**"),
    N = md("**N**")
    )
gtsave(tab, "~/data/projects/geo-rna-seq/results/normalization/figures/database-stats.png")
```

## Read in the database data

```{r}
# Extract into separate matrices
genes <- se[rowData(se)$feature_type == "gene", !is.na(se$epigenetic_class)]
repeats <- se[rowData(se)$feature_type == "re", !is.na(se$epigenetic_class)]
```

## PCA plots

```{r}
genes.lfc <- assay(genes, "lfc")
genes.res <- pca(genes.lfc, colData(genes), removeVar = 0.25)

p1 <- biplot(
  genes.res, 
  x = "PC3", 
  y = "PC4", 
  lab = NULL,
  colby = "epigenetic_class", 
  hline = 0, 
  vline = 0, 
  hlineType = 2, 
  vlineType = 2,
  title = "Protein Coding Genes",
  legendPosition = "bottom"
  ) +
  labs(color = "Epigenetic Class") +
  scale_color_brewer(palette = "Set1")
```

Repeat elements

```{r}
repeats.lfc <- assay(repeats, "lfc")
repeats.res <- pca(repeats.lfc, colData(repeats), removeVar = 0.25)

p2 <- biplot(
  repeats.res, 
  x = "PC1", 
  y = "PC2", 
  colby = "epigenetic_class",
  lab = NULL,
  hline = 0, 
  vline = 0, 
  hlineType = 2, 
  vlineType = 2, 
  title = "Repetitive Elements",
  legendPosition = "bottom"
  ) +
  labs(color = "Epigenetic Class") +
  scale_color_brewer(palette = "Set1")
```

Patch together

```{r}
(p1 | p2) +
  plot_layout(guides = "collect") +
  plot_annotation(title = "PCA on logFC")
ggsave(here("results", "combined", "figures", "pca.png"), width = 18, height = 8)
```

