---
title: "PCA Aza"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in differential expression results

```{r}
suppressPackageStartupMessages(library(SummarizedExperiment))
library(here)
library(data.table)
library(PCAtools)


se <- readRDS(here("results", "combined", "rds-files", "se.rds"))
```

## Subset for DNMTi only samples

```{r}
dnmti <- se[, se$epigenetic_class %like% "DNMTi" & se$drug %like% "Azacitidine|Decitabine"]
pca.dnmti <- pca(assay(dnmti, "lfc"), metadata = colData(dnmti), scale = FALSE, center = TRUE, removeVar = 0.1)

biplot(
  pca.dnmti,
  colby = "drug",
  lab = colData(dnmti)$dose,
  hline = 0,
  hlineType = 2,
  vline = 0,
  vlineType = 2,
  title = "Azacitidine & Decitabine LogFC",
  legendPosition = "bottom", 
  ) +
  scale_color_brewer(palette = "Set1")
ggsave(here("results","jozef", "figures", "pca-AzaDac.png"), width = 8, height = 6)
```

### Facet

```{r}
library(ggplot2)


dt <- setDT(pca.dnmti$rotated, keep.rownames = "id")
metadata <- setDT(data.frame(pca.dnmti$metadata, keep.rownames = "id"))
dt <- merge(dt, metadata, by = "id", all.x = TRUE, all.y = FALSE)

ggplot(dt, aes(PC1, PC2, color = drug)) +
  geom_point(size = 3) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_vline(xintercept = 0, linetype = 2) +
  facet_wrap(~drug) +
  labs(title = "PCA on LogFC of selected DNMTi",
       x = "PC1, 17.71%",
       y = "PC2, 14.46%") +
  theme_light() +
  scale_color_brewer(palette = "Set1") +
  theme(legend.position = "bottom", plot.title = element_text(size = 14, face = "bold"))
ggsave(here("results","jozef", "figures", "pca-AzaDac-facet.png"), width = 8, height = 6)
```



### Remove the outliers

```{r}
outlier_ids <- c()
dnmti.no <- dnmti[]
```



## Only HH1 experiment

```{r}
hh1 <- se[, se$experiment %like% "PRJNA413957" & !se$drug %like% "Tet Off"]
pca.hh1 <- pca(assay(hh1, "lfc"), metadata = colData(hh1), scale = FALSE, center = TRUE, removeVar = 0.1)

biplot(
  pca.hh1,
  colby = "drug",
  lab = NULL,
  hline = 0,
  hlineType = 2,
  vline = 0,
  vlineType = 2,
  title = "PCA on PRJNA413957 (HH1 Experiment) LogFC",
  legendPosition = "bottom"
  ) +
  scale_color_brewer(palette = "Dark2")
ggsave(here("results","jozef", "figures", "pca-PRJNA413957.png"), width = 8, height = 6)
```

##
