---
title: "HH1 Clean Contrasts"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in original DE files

renamed to '...original.tsv'

```{r}
library(data.table)
library(here)


dge <- fread(here("results", "hh1", "data-files", "dge.original.tsv"))
dre <- fread(here("results", "hh1", "data-files", "dre.original.tsv"))
```

## Rename contrasts

```{r}
unique(dge$contrast)


dge[, contrast := fcase(
  contrast == "hh1_2hr", "HH1.10uM_vs_DMSO_2hr",
  contrast == "hh1_4hr", "HH1.10uM_vs_DMSO_4hr",
  contrast == "hh1_8hr", "HH1.10uM_vs_DMSO_8hr",
  contrast == "hh1_24hr", "HH1.10uM_vs_DMSO_24hr",
  contrast == "hh1_96hr", "HH1.10uM_vs_DMSO_96hr",
  contrast == "hh1_25um_96hr", "HH1.25uM_vs_DMSO_96hr",
  contrast == "dac_96hr", "Decitabine_vs_DMSO_96hr",
  contrast == "dac_hh1_10um_96hr", "Decitabine_HH1.10uM_vs_DMSO_96hr",
  contrast == "dac_hh1_25um_96hr", "Decitabine_HH1.25uM_vs_DMSO_96hr",
  contrast == "tetOff", "tetOff_vs_tetOn_72hr",
  default = "UNKNOWN")]

dre[, contrast := fcase(
  contrast == "hh1_2hr", "HH1.10uM_vs_DMSO_2hr",
  contrast == "hh1_4hr", "HH1.10uM_vs_DMSO_4hr",
  contrast == "hh1_8hr", "HH1.10uM_vs_DMSO_8hr",
  contrast == "hh1_24hr", "HH1.10uM_vs_DMSO_24hr",
  contrast == "hh1_96hr", "HH1.10uM_vs_DMSO_96hr",
  contrast == "hh1_25um_96hr", "HH1.25uM_vs_DMSO_96hr",
  contrast == "dac_96hr", "Decitabine_vs_DMSO_96hr",
  contrast == "dac_hh1_10um_96hr", "Decitabine_HH1.10uM_vs_DMSO_96hr",
  contrast == "dac_hh1_25um_96hr", "Decitabine_HH1.25uM_vs_DMSO_96hr",
  contrast == "tetOff", "tetOff_vs_tetOn_72hr",
  default = "UNKNOWN")]
```

## Write out

```{r}
fwrite(dge, here("results", "hh1", "data-files", "dge.tsv"), sep = "\t")
fwrite(dre, here("results", "hh1", "data-files", "dre.tsv"), sep = "\t")
```

