---
title: "PRJNA246529 Analysis"
output:
  html_document:
    df_print: paged
    highlight: tango
    theme: united
    toc: yes
    toc_depth: 4
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

library(tidyverse)
library(here)
source("helpers/helpers.R")
```

## Read in SummarizedExperiment Object

```{r}
library(SummarizedExperiment)


se <- read_rds(here("data", "PRJNA246529", "summarized_experiment.rds"))
```

## Read in gene annotations

```{r}
cds <- read_rds(here("doc", "gencode.v26.annotation.cds.rds"))
```

## Filter out RNA REs from counts assay

```{r}
se <- subset(se, !str_detect(rownames(se), "tRNA|snRNA|scRNA|rRNA|srpRNA|Simple_repeat|Low_complexity"))
```

## DE pipeline

```{r}
library(edgeR)
library(coriell)


design <- model.matrix(~0 + group, data = colData(se))
colnames(design) <- str_remove(colnames(design), "^group")
y <- DGEList(counts = assay(se, "counts"),
             samples = colData(se))
keep <- filterByExpr(y, design = design)
y <- y[keep,, keep.lib.sizes = FALSE]
y <- calcNormFactors(y, design = design, method = "TMM")
y <- estimateDisp(y, design = design, robust = TRUE)
fit <- glmQLFit(y, design = design, robust = TRUE)
```

## NO DE TESTING FOR THIS DATASET

There are no contrasts to test -- only expression data.

## Calculate normalized counts

```{r}
lcpms <- cpm(y, log = TRUE, prior.count = 2)

# split lcpms by gene and by RE
lcpms.gene <- subset(lcpms, rownames(lcpms) %in% cds$gene_name)
lcpms.re <- subset(lcpms, !rownames(lcpms) %in% cds$gene_name)

# Write normalized counts out
write_rds(lcpms.gene, here("results", "PRJNA246529", "rds-files", "gene-lcpms.rds"))
write_rds(lcpms.re, here("results", "PRJNA246529", "rds-files", "re-lcpms.rds"))
```
