---
title: "PRJNA335388 Analysis"
output:
  html_document:
    df_print: paged
    highlight: tango
    theme: united
    toc: yes
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

source("helpers/helpers.R")
```

## Read in SummarizedExperiment Object

```{r}
library(tidyverse)
library(here)
library(SummarizedExperiment)


se <- readRDS(here("data", "PRJNA335388", "summarized_experiment.rds"))
```

## Read in gene annotations

```{r}
gtf <- rtracklayer::import("/mnt/data/data_gc/projects/yb5-combined-analysis/doc/gencode.v26.annotation.gtf.gz")
gtf_df <- as.data.frame(gtf)
cds <- subset(gtf_df, 
              type == "gene" & gene_type == "protein_coding", 
              c("gene_id", "gene_name", "seqnames", "start", "end", "width", "strand")
              )
```

## Filter out RNA REs from counts assay

```{r}
se <- subset(se, !str_detect(rownames(se), "tRNA|snRNA|scRNA|rRNA|srpRNA|Simple_repeat|Low_complexity"))
```

## DE pipeline

```{r}
library(edgeR)
library(coriell)


design <- model.matrix(~0 + group, data = colData(se))
colnames(design) <- str_remove(colnames(design), "^group")
y <- DGEList(counts = assay(se, "counts"),
             samples = colData(se)) 
keep <- filterByExpr(y, design = design)
y <- y[keep,, keep.lib.sizes = FALSE]
y <- calcNormFactors(y, design = design, method = "TMM")
y <- estimateDisp(y, design = design, robust = TRUE)
fit <- glmQLFit(y, design = design, robust = TRUE)
```

## DE testing

```{r}
contrast.matrix <- makeContrasts(
  bc_dox = MDA.doxorubicin_1uM - MDA.dmso,
  bc_eto = MDA.etoposide_20uM - MDA.dmso,
  bc_mms = MDA.mms_40ug_ml - MDA.dmso,
  bc_pac = MDA.paclitaxel_0.2uM - MDA.dmso,
  os_dox = U2OS.doxorubicin_1uM - U2OS.dmso,
  os_eto = U2OS.etoposide_20uM - U2OS.dmso,
  os_mms = U2OS.mms_40ug_ml - U2OS.dmso,
  os_pac = U2OS.paclitaxel_0.2uM - U2OS.dmso,
  
  levels = design
)

# create inputs to map over (titles are same as above)
cons <- colnames(contrast.matrix)
names(cons) <- cons
titles <- c("Breast Cancer - Doxorubicin.1uM",
            "Breast Cancer - Etoposide.20uM",
            "Breast Cancer - MMS.40ug_ml",
            "Breast Cancer - Paclitaxel.0.2uM",
            "Osteosarcoma - Doxorubicin.1uM",
            "Osteosarcoma - Etoposide.20uM",
            "Osteosarcoma - MMS.40ug_ml",
            "Osteosarcoma - Paclitaxel.0.2uM")

# set global significance levels (used in all downstream plots/analyses)
fc <- 1.5
sig <- 0.1

# map over and extract results
de_results <- map2(.x = cons, 
                   .y = titles, 
                   .f = get_de_results, 
                    contrast_matrix = contrast.matrix,
                    fdr = sig,
                    fc = fc,
                    glm_fit = fit)

# extract all results and bind to single df
df <- map(de_results, pluck, "table") %>% bind_rows(.id = "contrast")
```

## Write results out

```{r}
# split DE results into gene and RE results and write out
dge <- df %>% 
  filter(feature_id %in% cds$gene_name) %>% 
  write_tsv(here("results", "PRJNA335388", "data-files", "dge.tsv"))

dre <- df %>% 
  filter(!feature_id %in% cds$gene_name) %>% 
  write_tsv(here("results", "PRJNA335388", "data-files", "dre.tsv"))
```

## Create plots for each contrast 

```{r}
coi <- names(de_results)
gene_vplots <- vector("list", length(coi))
gene_mdplots <- vector("list", length(coi))
re_vplots <- vector("list", length(coi))
re_mdplots <- vector("list", length(coi))

for (i in seq_along(coi)) {
  gene_vplots[[i]] <- 
    dge %>%
    filter(contrast == coi[[i]]) %>% 
    plot_volcano(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
  
  gene_mdplots[[i]] <- 
    dge %>%
    filter(contrast == coi[[i]]) %>% 
    plot_md(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
  
  re_vplots[[i]] <- 
    dre %>% 
    filter(contrast == coi[[i]]) %>% 
    plot_volcano(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
  
  re_mdplots[[i]] <- 
    dre %>% 
    filter(contrast == coi[[i]]) %>% 
    plot_md(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
}
```

## Calculate normalized counts

```{r}
lcpms <- cpm(y, log = TRUE, prior.count = 2)

# split lcpms by gene and by RE
lcpms.gene <- subset(lcpms, rownames(lcpms) %in% cds$gene_name)
lcpms.re <- subset(lcpms, !rownames(lcpms) %in% cds$gene_name)

# Write normalized counts out
write_rds(lcpms.gene, here("results", "PRJNA335388", "rds-files", "gene-lcpms.rds"))
write_rds(lcpms.re, here("results", "PRJNA335388", "rds-files", "re-lcpms.rds"))
```

## PCA

```{r}
library(FactoMineR)
library(factoextra)


# perform PCA with factominer --------------------------------------------------
pca.gene <- PCA(t(lcpms.gene),
                scale.unit = TRUE,
                graph = FALSE,
                ncp = 5)

pca.re <- PCA(t(lcpms.re),
              scale.unit = TRUE,
              graph = FALSE,
              ncp = 5)

# scree plot -------------------------------------------------------------------
fviz_eig(pca.gene, addlabels = TRUE) +
  ggtitle("Protein Coding Genes") +
  ggsave(here("results", "PRJNA335388", "figures", "gene-scree.png"),
         width = 8,
         height = 5)

fviz_eig(pca.re, addlabels = TRUE) +
  ggtitle("Repetitive Elements") +
  ggsave(here("results", "PRJNA335388", "figures", "re-scree.png"),
         width = 8,
         height = 5)

# extract the individual level coordinates -------------------------------------
ind.gene <- get_pca_ind(pca.gene)
ind.re <- get_pca_ind(pca.re)

# plot -------------------------------------------------------------------------
# genes
ind.gene$coord %>% 
  as_tibble(rownames = "sample_name") %>% 
  left_join(as_tibble(colData(se), rownames = "sample_name"), by = "sample_name") %>% 
  ggplot(aes(x = Dim.1, y = Dim.2, color = drug, shape = cell_type)) +
  geom_point(size = 5) +
  geom_hline(yintercept = 0, linetype = 3) +
  geom_vline(xintercept = 0, linetype = 3) +
  labs(title = "Protein Coding Genes",
       x = "PC 1",
       y = "PC 2") +
  scale_color_brewer(palette = "Dark2") +
  theme_light() +
  ggsave(here("results", "PRJNA335388", "figures", "gene-pca.png"),
         width = 8,
         height = 5)
# REs
ind.re$coord %>% 
  as_tibble(rownames = "sample_name") %>% 
  left_join(as_tibble(colData(se), rownames = "sample_name"), by = "sample_name") %>% 
  ggplot(aes(x = Dim.1, y = Dim.2, color = drug, shape = cell_type)) +
  geom_point(size = 5) +
  geom_hline(yintercept = 0, linetype = 3) +
  geom_vline(xintercept = 0, linetype = 3) +
  labs(title = "Repetitive Elements",
       x = "PC 1",
       y = "PC 2") +
  scale_color_brewer(palette = "Dark2") +
  theme_light() +
  ggsave(here("results", "PRJNA335388", "figures", "re-pca.png"),
         width = 8,
         height = 5)
```

## Heatmaps

```{r}
# create column annotation
col_df <- colData(se)[, c("cell_type", "drug")] %>% as.data.frame()

# create colors for column annotations
cell_colors <- c("firebrick", "steelblue")
drug_colors <- RColorBrewer::brewer.pal(n = length(unique(col_df$drug)), "Dark2")

names(cell_colors) <- unique(col_df$cell_type)
names(drug_colors) <- unique(col_df$drug)

# put colors in list
ann_colors <- list(cell_type = cell_colors, drug = drug_colors)

# extract only significant genes and REs ---------------------------------------
sig_genes <- df %>% filter(feature_id %in% cds$gene_name & FDR < sig) %>% pull(feature_id)
sig_res <- df %>% filter(!feature_id %in% cds$gene_name & FDR < sig) %>% pull(feature_id)
lcpms.sig_genes <- subset(lcpms.gene, rownames(lcpms.gene) %in% sig_genes)
lcpms.sig_res <- subset(lcpms.re, rownames(lcpms.re) %in% sig_res)

# plot heatmaps ----------------------------------------------------------------
quickmap(lcpms.sig_genes, 
         annotation_col = col_df,
         annotation_colors = ann_colors,
         main = paste("Significant (FDR <", sig, ") Protein Coding Genes"),
         filename = here("results", "PRJNA335388", "figures", "gene-heatmap.png"))

quickmap(lcpms.sig_res, 
         annotation_col = col_df,
         annotation_colors = ann_colors,
         main = paste("Significant (FDR <", sig, ") Repetitive Elements"),
         filename = here("results", "PRJNA335388", "figures", "re-heatmap.png"))
```

## Create patchworks

```{r}
library(patchwork)


# Gene-level -------------------------------------------------------------------
(gene_vplots[[1]] + scale_y_continuous(limits = c(0, 5)) + scale_x_continuous(limits = c(-10, 10)) | 
 gene_vplots[[2]] + scale_y_continuous(limits = c(0, 5)) + scale_x_continuous(limits = c(-10, 10)) | 
 gene_vplots[[3]] + scale_y_continuous(limits = c(0, 5)) + scale_x_continuous(limits = c(-10, 10)) | 
 gene_vplots[[4]] + scale_y_continuous(limits = c(0, 5)) + scale_x_continuous(limits = c(-10, 10))) /
(gene_vplots[[5]] + scale_y_continuous(limits = c(0, 5)) + scale_x_continuous(limits = c(-10, 10)) | 
 gene_vplots[[6]] + scale_y_continuous(limits = c(0, 5)) + scale_x_continuous(limits = c(-10, 10)) | 
 gene_vplots[[7]] + scale_y_continuous(limits = c(0, 5)) + scale_x_continuous(limits = c(-10, 10)) | 
 gene_vplots[[8]] + scale_y_continuous(limits = c(0, 5)) + scale_x_continuous(limits = c(-10, 10))) +
 plot_layout(guides = "collect") +
 ggsave(here("results", "PRJNA335388", "figures", "gene-vplots.png"), 
        width = 18,
        height = 10)

(gene_mdplots[[1]] | 
 gene_mdplots[[2]] | 
 gene_mdplots[[3]] | 
 gene_mdplots[[4]]) /
(gene_mdplots[[5]] | 
 gene_mdplots[[6]] | 
 gene_mdplots[[7]] | 
 gene_mdplots[[8]]) +
 plot_layout(guides = "collect") +
 ggsave(here("results", "PRJNA335388", "figures", "gene-mdplots.png"), 
        width = 18,
        height = 10)

# RE-level -------------------------------------------------------------------
(re_vplots[[1]] + scale_y_continuous(limits = c(0, 4)) + scale_x_continuous(limits = c(-10, 10)) | 
 re_vplots[[2]] + scale_y_continuous(limits = c(0, 4)) + scale_x_continuous(limits = c(-10, 10)) | 
 re_vplots[[3]] + scale_y_continuous(limits = c(0, 4)) + scale_x_continuous(limits = c(-10, 10)) | 
 re_vplots[[4]] + scale_y_continuous(limits = c(0, 4)) + scale_x_continuous(limits = c(-10, 10))) /
(re_vplots[[5]] + scale_y_continuous(limits = c(0, 4)) + scale_x_continuous(limits = c(-10, 10)) | 
 re_vplots[[6]] + scale_y_continuous(limits = c(0, 4)) + scale_x_continuous(limits = c(-10, 10)) | 
 re_vplots[[7]] + scale_y_continuous(limits = c(0, 4)) + scale_x_continuous(limits = c(-10, 10)) | 
 re_vplots[[8]] + scale_y_continuous(limits = c(0, 4)) + scale_x_continuous(limits = c(-10, 10))) +
 plot_layout(guides = "collect") +
 ggsave(here("results", "PRJNA335388", "figures", "re-vplots.png"), 
        width = 18,
        height = 10)

(re_mdplots[[1]] | 
 re_mdplots[[2]] | 
 re_mdplots[[3]] | 
 re_mdplots[[4]]) /
(re_mdplots[[5]] | 
 re_mdplots[[6]] | 
 re_mdplots[[7]] | 
 re_mdplots[[8]]) +
 plot_layout(guides = "collect") +
 ggsave(here("results", "PRJNA335388", "figures", "re-mdplots.png"), 
        width = 18,
        height = 10)
```

## Create Family-Level Dotplots for significant REs

```{r}
dotplots <- vector("list", length(names(de_results)))
for (i in seq_along(names(de_results))) {
  dotplots[[i]] <- plot_fam_counts(dre, names(de_results)[[i]], n_dots = 20)
}

(dotplots[[1]] + ggtitle(titles[[1]]) | 
 dotplots[[2]] + ggtitle(titles[[2]]) | 
 plot_spacer()) / 
(dotplots[[5]] + ggtitle(titles[[5]]) | 
 dotplots[[6]] + ggtitle(titles[[6]]) | 
 dotplots[[7]] + ggtitle(titles[[7]])) +
 ggsave(here("results", "PRJNA335388", "figures", "dotplots.png"),
        width = 18,
        height = 10)
```

## Plot RE expression relative to all genes + REs

```{r}
# RE expression in BC Doxo -----------------------------------------------------
df %>% 
  filter(contrast == "bc_dox") %>% 
  ggplot(aes(x = logCPM, y = logFC)) +
  geom_point(alpha = 0.05) +
  geom_point(data = {dre %>% filter(contrast == "bc_dox" & FDR < sig)},
             color = "red",
             alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = 3) +
  theme_bw() +
  labs(title = titles[[1]],
       subtitle = "Significant REs Highlighted in Red") +
  ggsave(here("results", "PRJNA335388", "figures", "bc_dox-mdplot.png"), 
         width = 8,
         height = 5)

df %>% 
  filter(contrast == "os_dox") %>% 
  ggplot(aes(x = logCPM, y = logFC)) +
  geom_point(alpha = 0.05) +
  geom_point(data = {dre %>% filter(contrast == "os_dox" & FDR < sig)},
             color = "red",
             alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = 3) +
  theme_bw() +
  labs(title = titles[[5]],
       subtitle = "Significant REs Highlighted in Red") +
  ggsave(here("results", "PRJNA335388", "figures", "os_dox-mdplot.png"), 
         width = 8,
         height = 5)
```

