---
title: "PRJNA400080 Analysis"
output:
  html_document:
    df_print: paged
    highlight: tango
    theme: united
    toc: yes
    toc_depth: 4
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
source("helpers/helpers.R")
```

## Read in MultiAssayExperiment Object

```{r}
library(here)
library(data.table)
library(MultiAssayExperiment)


mae <- readRDS(here("data", "PRJNA400080", "MultiAssayExperiment.rds"))
```

## Read in gene annotations

```{r}
cds <- readRDS(here("doc", "gencode.v26.annotation.cds.rds"))
```

## Extract RE and Gene Counts as matrices

```{r}
genes <- assay(mae, "gene counts")
repeats <- assay(mae, "RE counts")
```

## Restrict REs to five classes

LINE, SINE, long terminal repeats (LTR), SVA, and DNA transposons

```{r}
repeats <- subset(repeats, grepl(rownames(repeats), pattern = "^LINE\\.|^SINE\\.|^LTR\\.|.*\\.SVA\\..*|^DNA\\."))
```

## Restrict genes to protein coding

```{r}
genes <- subset(genes, rownames(genes) %in% cds$gene_name)
```

## Combine both matrices into a single count matrix

```{r}
# check for consistent colnames
all(colnames(genes) == colnames(repeats))

# bind both matrices into single count matrix
counts <- rbind(genes, repeats)
```

## DE pipeline

```{r}
design <- model.matrix(~0 + group, data = colData(mae))
colnames(design) <- gsub(pattern = "^group", replacement = "", x = colnames(design))
y <- DGEList(counts = counts, samples = colData(mae))
keep <- filterByExpr(y, design = design)
y <- y[keep,, keep.lib.sizes = FALSE]
y <- calcNormFactors(y, design = design, method = "TMM")
y <- estimateDisp(y, design = design, robust = TRUE)
fit <- glmQLFit(y, design = design, robust = TRUE)
```

## DE testing

```{r}
contrast.matrix <- makeContrasts(
  BI00894999.1nM_vs_DMSO_4hr = BI00894999.1nM.4 - DMSO.NA.4,
  BI00894999.1nM_vs_DMSO_24hr = (BI00894999.1nM.24 - BI00894999.1nM.4) - (DMSO.NA.24 - DMSO.NA.4),
  BI00894999.35nM_vs_DMSO_4hr = BI00894999.35nM.4 - DMSO.NA.4,
  BI00894999.35nM_vs_DMSO_24hr = (BI00894999.35nM.24 - BI00894999.35nM.4) - (DMSO.NA.24 - DMSO.NA.4),
  BI00894999_Volasertib.1nM_20nM_vs_DMSO_4hr = BI00894999_Volasertib.1nM_20nM.4 - DMSO.NA.4,
  BI00894999_Volasertib.1nM_20nM_vs_DMSO_24hr = (BI00894999_Volasertib.1nM_20nM.24 - BI00894999_Volasertib.1nM_20nM.4) -
                                                (DMSO.NA.24 - DMSO.NA.4),
  BI00894999_Volasertib.35nM_20nM_vs_DMSO_4hr = BI00894999_Volasertib.35nM_20nM.4 - DMSO.NA.4,
  BI00894999_Volasertib.35nM_20nM_vs_DMSO_24hr = (BI00894999_Volasertib.35nM_20nM.24 - BI00894999_Volasertib.35nM_20nM.4) -
                                                 (DMSO.NA.24 - DMSO.NA.4),
  Volasertib.20nM_vs_DMSO_4hr = Volasertib.20nM.4 - DMSO.NA.4,
  Volasertib.20nM_vs_DMSO_24hr = (Volasertib.20nM.24 - Volasertib.20nM.4) - (DMSO.NA.24 - DMSO.NA.4),
  
  levels = design
)

# create inputs to map over (titles are same as above)
cons <- colnames(contrast.matrix)
names(cons) <- cons

# set global significance levels (used in all downstream plots/analyses)
fc <- 1.5

# map over and extract results
de_results <- lapply(
  cons, 
  get_de_results2, 
  contrast_matrix = contrast.matrix,
  fc = fc,
  glm_fit = fit
)

# extract all results and bind to single df
df <- rbindlist(lapply(de_results, function(x) x[["table"]]), idcol = "contrast")
```

## Write results out

```{r}
# split DE results into gene and RE results and write out
fwrite(
  x = df[feature_id %chin% cds$gene_name],
  file = here("results", "PRJNA400080", "data-files", "dge.tsv"),
  sep = "\t"
  )

fwrite(
  x = df[!feature_id %chin% cds$gene_name],
  file = here("results", "PRJNA400080", "data-files", "dre.tsv"),
  sep = "\t"
)
```

## Calculate normalized counts

```{r}
lcpms <- cpm(y, log = TRUE, prior.count = 2)

# split lcpms by gene and by RE
lcpms.gene <- subset(lcpms, rownames(lcpms) %in% cds$gene_name)
lcpms.re <- subset(lcpms, !rownames(lcpms) %in% cds$gene_name)

# Write normalized counts out
saveRDS(lcpms.gene, here("results", "PRJNA400080", "rds-files", "gene-lcpms.rds"))
saveRDS(lcpms.re, here("results", "PRJNA400080", "rds-files", "re-lcpms.rds"))
```
