---
title: "PRJNA315294 Analysis"
output:
  html_document:
    df_print: paged
    highlight: tango
    theme: united
    toc: yes
    toc_depth: 4
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

source("helpers/helpers.R")
```

## Read in SummarizedExperiment Object

```{r}
library(tidyverse)
library(here)
library(SummarizedExperiment)


se <- readRDS(here("data", "PRJNA315294", "summarized_experiment.rds"))
```

## Read in gene annotations

```{r}
gtf <- rtracklayer::import("/mnt/data/data_gc/projects/yb5-combined-analysis/doc/gencode.v26.annotation.gtf.gz")
gtf_df <- as.data.frame(gtf)
cds <- subset(gtf_df, 
              type == "gene" & gene_type == "protein_coding", 
              c("gene_id", "gene_name", "seqnames", "start", "end", "width", "strand")
              )
```

## Filter out RNA REs from counts assay

```{r}
se <- subset(se, !str_detect(rownames(se), "tRNA|snRNA|scRNA|rRNA|srpRNA|Simple_repeat|Low_complexity"))
```

## DE pipeline

```{r}
library(edgeR)
library(coriell)


design <- model.matrix(~0 + group, data = colData(se))
colnames(design) <- str_remove(colnames(design), "^group")
y <- DGEList(counts = assay(se, "counts"),
             samples = colData(se)) 
keep <- filterByExpr(y, design = design)
y <- y[keep,, keep.lib.sizes = FALSE]
y <- calcNormFactors(y, design = design, method = "TMM")
y <- estimateDisp(y, design = design, robust = TRUE)
fit <- glmQLFit(y, design = design, robust = TRUE)
```

## DE testing

```{r}
contrast.matrix <- makeContrasts(
  hct_wt_dox = HCT116.p53_WT.doxorubicin.300nM.16h - HCT116.p53_WT.control,
  hct_ko_dox = HCT116.p53_KO.doxorubicin.300nM.16h - HCT116.p53_KO.control,
  rko_wt_dox = RKO.p53_WT.doxorubicin.300nM.16h - RKO.p53_WT.control,
  rko_ko_dox = RKO.p53_KO.doxorubicin.300nM.16h -  RKO.p53_KO.control,
  sw48_wt_dox = SW48.p53_WT.doxorubicin.300nM.16h - SW48.p53_WT.control,
  sw48_ko_dox = SW48.p53_KO.doxorubicin.300nM.16h - SW48.p53_KO.control,
  hct_dox = ((HCT116.p53_WT.doxorubicin.300nM.16h + HCT116.p53_KO.doxorubicin.300nM.16h) / 2) - ((HCT116.p53_WT.control + HCT116.p53_KO.control) / 2), 
  rko_dox = ((RKO.p53_WT.doxorubicin.300nM.16h + RKO.p53_KO.doxorubicin.300nM.16h) / 2) - ((RKO.p53_WT.control + RKO.p53_KO.control) / 2),
  sw48_dox = ((SW48.p53_WT.doxorubicin.300nM.16h + SW48.p53_KO.doxorubicin.300nM.16h) / 2) - ((SW48.p53_WT.control + SW48.p53_KO.control) / 2),
  levels = design
)

# create inputs to map over (titles are same as above)
cons <- colnames(contrast.matrix)
names(cons) <- cons
titles <- c("HCT116 p53 WT + Doxorubicin 300nM vs. HCT116 p53 WT Control",
            "HCT116 p53 KO + Doxorubicin 300nM vs. HCT116 p53 KO Control",
            "RKO p53 WT + Doxorubicin 300nM vs. RKO p53 WT Control",
            "RKO p53 KO + Doxorubicin 300nM vs. RKO p53 KO Control",
            "SW48 p53 WT + Doxorubicin 300nM vs. SW48 p53 WT Control",
            "SW48 p53 KO + Doxorubicin 300nM vs. SW48 p53 KO Control",
            "HCT116 + Doxorubicin 300nM vs. HCT116 Control",
            "RKO + Doxorubicin 300nM vs. RKO Control",
            "SW48 + Doxorubicin 300nM vs SW48 Control")

# set global significance levels (used in all downstream plots/analyses)
fc <- 1.5
sig <- 0.1

# map over and extract results
de_results <- map2(.x = cons, 
                   .y = titles, 
                   .f = get_de_results, 
                    contrast_matrix = contrast.matrix,
                    fdr = sig,
                    fc = fc,
                    glm_fit = fit)

# extract all results and bind to single df
df <- map(de_results, pluck, "table") %>% bind_rows(.id = "contrast")
```

## Write results out

```{r}
# split DE results into gene and RE results and write out
dge <- df %>% 
  filter(feature_id %in% cds$gene_name) %>% 
  write_tsv(here("results", "PRJNA315294", "data-files", "dge.tsv"))

dre <- df %>% 
  filter(!feature_id %in% cds$gene_name) %>% 
  write_tsv(here("results", "PRJNA315294", "data-files", "dre.tsv"))
```

## Create plots for each contrast 

```{r}
coi <- names(de_results)
gene_vplots <- vector("list", length(coi))
gene_mdplots <- vector("list", length(coi))
re_vplots <- vector("list", length(coi))
re_mdplots <- vector("list", length(coi))

for (i in seq_along(coi)) {
  gene_vplots[[i]] <- 
    dge %>%
    filter(contrast == coi[[i]]) %>% 
    plot_volcano(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
  
  gene_mdplots[[i]] <- 
    dge %>%
    filter(contrast == coi[[i]]) %>% 
    plot_md(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
  
  re_vplots[[i]] <- 
    dre %>% 
    filter(contrast == coi[[i]]) %>% 
    plot_volcano(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
  
  re_mdplots[[i]] <- 
    dre %>% 
    filter(contrast == coi[[i]]) %>% 
    plot_md(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
}
```

## Calculate normalized counts

```{r}
lcpms <- cpm(y, log = TRUE, prior.count = 2)

# split lcpms by gene and by RE
lcpms.gene <- subset(lcpms, rownames(lcpms) %in% cds$gene_name)
lcpms.re <- subset(lcpms, !rownames(lcpms) %in% cds$gene_name)

# Write normalized counts out
write_rds(lcpms.gene, here("results", "PRJNA315294", "rds-files", "gene-lcpms.rds"))
write_rds(lcpms.re, here("results", "PRJNA315294", "rds-files", "re-lcpms.rds"))
```

## PCA

```{r}
library(FactoMineR)
library(factoextra)


# perform PCA with factominer --------------------------------------------------
pca.gene <- PCA(t(lcpms.gene),
                scale.unit = TRUE,
                graph = FALSE,
                ncp = 5)

pca.re <- PCA(t(lcpms.re),
              scale.unit = TRUE,
              graph = FALSE,
              ncp = 5)

# scree plot -------------------------------------------------------------------
fviz_eig(pca.gene, addlabels = TRUE) +
  ggtitle("Protein Coding Genes") +
  ggsave(here("results", "PRJNA315294", "figures", "gene-scree.png"),
         width = 8,
         height = 5)

fviz_eig(pca.re, addlabels = TRUE) +
  ggtitle("Repetitive Elements") +
  ggsave(here("results", "PRJNA315294", "figures", "re-scree.png"),
         width = 8,
         height = 5)

# extract the individual level coordinates -------------------------------------
ind.gene <- get_pca_ind(pca.gene)
ind.re <- get_pca_ind(pca.re)

# plot -------------------------------------------------------------------------
# genes
ind.gene$coord %>% 
  as_tibble(rownames = "sample_name") %>% 
  left_join(as_tibble(colData(se), rownames = "sample_name"), by = "sample_name") %>% 
  separate(group, into = c("cell_type", "mutation", "treatment"), sep = "\\.") %>%
  unite(cell_type, cell_type, mutation, sep = ".") %>% 
  ggplot(aes(x = Dim.1, y = Dim.2, color = cell_type, shape = treatment)) +
  geom_point(size = 5) +
  geom_hline(yintercept = 0, linetype = 3) +
  geom_vline(xintercept = 0, linetype = 3) +
  labs(title = "Protein Coding Genes",
       x = "PC 1",
       y = "PC 2") +
  scale_color_brewer(palette = "Paired") +
  theme_light() +
  ggsave(here("results", "PRJNA315294", "figures", "gene-pca.png"),
         width = 8,
         height = 5)
# REs
ind.re$coord %>% 
  as_tibble(rownames = "sample_name") %>% 
  left_join(as_tibble(colData(se), rownames = "sample_name"), by = "sample_name") %>% 
  separate(group, into = c("cell_type", "mutation", "treatment"), sep = "\\.") %>%
  unite(cell_type, cell_type, mutation, sep = ".") %>% 
  ggplot(aes(x = Dim.1, y = Dim.2, color = cell_type, shape = treatment)) +
  geom_point(size = 5) +
  geom_hline(yintercept = 0, linetype = 3) +
  geom_vline(xintercept = 0, linetype = 3) +
  labs(title = "Repetitive Elements",
       x = "PC 1",
       y = "PC 2") +
  scale_color_brewer(palette = "Paired") +
  theme_light() +
  ggsave(here("results", "PRJNA315294", "figures", "re-pca.png"),
         width = 8,
         height = 5)
```

## Heatmaps

```{r}
# create column annotation
col_df <- as.data.frame(colData(se)) %>% 
  separate(group, into = c("cell_type", "mutation", "treatment"), sep = "\\.")

# create colors for column annotations
cell_colors <- RColorBrewer::brewer.pal(n = length(unique(col_df$cell_type)), "Dark2")
mut_colors <- c("#543005", "#003C30")
trt_colors <- c("steelblue", "firebrick")
names(cell_colors) <- unique(col_df$cell_type)
names(mut_colors) <- unique(col_df$mutation)
names(trt_colors) <- unique(col_df$treatment)

# put colors in list
ann_colors <- list(cell_type = cell_colors, mutation = mut_colors, treatment = trt_colors)

# extract only significant genes and REs ---------------------------------------
sig_genes <- df %>% filter(feature_id %in% cds$gene_name & FDR < sig) %>% pull(feature_id)
sig_res <- df %>% filter(!feature_id %in% cds$gene_name & FDR < sig) %>% pull(feature_id)
lcpms.sig_genes <- subset(lcpms.gene, rownames(lcpms.gene) %in% sig_genes)
lcpms.sig_res <- subset(lcpms.re, rownames(lcpms.re) %in% sig_res)

# plot heatmaps ----------------------------------------------------------------
quickmap(lcpms.sig_genes, 
         annotation_col = col_df,
         annotation_colors = ann_colors,
         main = paste("Significant (FDR <", sig, ") Protein Coding Genes"),
         filename = here("results", "PRJNA315294", "figures", "gene-heatmap.png"))

quickmap(lcpms.sig_res, 
         annotation_col = col_df,
         annotation_colors = ann_colors,
         main = paste("Significant (FDR <", sig, ") Repetitive Elements"),
         filename = here("results", "PRJNA315294", "figures", "re-heatmap.png"))
```

## Create patchworks

```{r}
library(patchwork)


# Gene-level -------------------------------------------------------------------
(gene_vplots[[1]] + scale_y_continuous(limits = c(0, 3)) | gene_vplots[[2]] + scale_y_continuous(limits = c(0, 3))) / 
(gene_vplots[[3]] + scale_y_continuous(limits = c(0, 3)) | gene_vplots[[4]] + scale_y_continuous(limits = c(0, 3))) /
(gene_vplots[[5]] + scale_y_continuous(limits = c(0, 3)) | gene_vplots[[6]] + scale_y_continuous(limits = c(0, 3))) +
  plot_layout(guides = "collect") +
  plot_annotation("Protein Coding Gene Expression - KO treated vs WT untreated") +
  ggsave(here("results", "PRJNA315294", "figures", "gene-vplot-muts.png"),
         width = 15, 
         height = 12)

(gene_vplots[[7]] + scale_y_continuous(limits = c(0, 2)) + scale_x_continuous(limits = c(-10, 10)) | 
 gene_vplots[[8]] + scale_y_continuous(limits = c(0, 2)) + scale_x_continuous(limits = c(-10, 10)) | 
 gene_vplots[[9]] + scale_y_continuous(limits = c(0, 2)) + scale_x_continuous(limits = c(-10, 10))) +
  plot_layout(guides = "collect") +
  plot_annotation("Protein Coding Gene Expression - KO+WT treated vs KO+WT untreated") +
  ggsave(here("results", "PRJNA315294", "figures", "gene-vplot.png"),
         width = 18, 
         height = 8)

(gene_mdplots[[1]] + scale_y_continuous(limits = c(-10, 10)) | gene_mdplots[[2]] + scale_y_continuous(limits = c(-10, 10))) / 
(gene_mdplots[[3]] + scale_y_continuous(limits = c(-10, 10)) | gene_mdplots[[4]] + scale_y_continuous(limits = c(-10, 10))) /
(gene_mdplots[[5]] + scale_y_continuous(limits = c(-10, 10)) | gene_mdplots[[6]] + scale_y_continuous(limits = c(-10, 10))) +
  plot_layout(guides = "collect") +
  plot_annotation("Protein Coding Gene Expression - KO treated vs WT untreated") +
  ggsave(here("results", "PRJNA315294", "figures", "gene-mdplot-muts.png"),
         width = 15, 
         height = 12)

(gene_mdplots[[7]] + scale_y_continuous(limits = c(-10, 10)) | 
 gene_mdplots[[8]] + scale_y_continuous(limits = c(-10, 10)) | 
 gene_mdplots[[9]] + scale_y_continuous(limits = c(-10, 10))) +
  plot_layout(guides = "collect") +
  plot_annotation("Protein Coding Gene Expression - KO+WT treated vs KO+WT untreated") +
  ggsave(here("results", "PRJNA315294", "figures", "gene-mdplot.png"),
         width = 18, 
         height = 8)

# RE-level ---------------------------------------------------------------------
(re_vplots[[1]] + scale_y_continuous(limits = c(0, 2)) | re_vplots[[2]] + scale_y_continuous(limits = c(0, 2))) / 
(re_vplots[[3]] + scale_y_continuous(limits = c(0, 2)) | re_vplots[[4]] + scale_y_continuous(limits = c(0, 2))) /
(re_vplots[[5]] + scale_y_continuous(limits = c(0, 2)) | re_vplots[[6]] + scale_y_continuous(limits = c(0, 2))) +
  plot_layout(guides = "collect") +
  plot_annotation("RE Expression - KO treated vs WT untreated") +
  ggsave(here("results", "PRJNA315294", "figures", "re-vplot-muts.png"),
         width = 15, 
         height = 12)

(re_vplots[[7]] + scale_y_continuous(limits = c(0, 1.5)) + scale_x_continuous(limits = c(-5, 5)) | 
 re_vplots[[8]] + scale_y_continuous(limits = c(0, 1.5)) + scale_x_continuous(limits = c(-5, 5)) | 
 re_vplots[[9]] + scale_y_continuous(limits = c(0, 1.5)) + scale_x_continuous(limits = c(-5, 5))) +
  plot_layout(guides = "collect") +
  plot_annotation("RE Expression - KO+WT treated vs KO+WT untreated") +
  ggsave(here("results", "PRJNA315294", "figures", "re-vplot.png"),
         width = 18, 
         height = 8)

(re_mdplots[[1]] + scale_y_continuous(limits = c(-10, 10)) | re_mdplots[[2]] + scale_y_continuous(limits = c(-10, 10))) / 
(re_mdplots[[3]] + scale_y_continuous(limits = c(-10, 10)) | re_mdplots[[4]] + scale_y_continuous(limits = c(-10, 10))) /
(re_mdplots[[5]] + scale_y_continuous(limits = c(-10, 10)) | re_mdplots[[6]] + scale_y_continuous(limits = c(-10, 10))) +
  plot_layout(guides = "collect") +
  plot_annotation("RE Expression - KO treated vs WT untreated") +
  ggsave(here("results", "PRJNA315294", "figures", "re-mdplot-muts.png"),
         width = 15, 
         height = 12)

(re_mdplots[[7]] + scale_y_continuous(limits = c(-10, 10)) | 
 re_mdplots[[8]] + scale_y_continuous(limits = c(-10, 10)) | 
 re_mdplots[[9]] + scale_y_continuous(limits = c(-10, 10))) +
  plot_layout(guides = "collect") +
  plot_annotation("RE Expression - KO+WT treated vs KO+WT untreated") +
  ggsave(here("results", "PRJNA315294", "figures", "re-mdplot.png"),
         width = 18, 
         height = 8)
```

## Create Family-Level Dotplots for significant REs

```{r}
dotplots <- vector("list", length(names(de_results)))
for (i in seq_along(names(de_results))) {
  dotplots[[i]] <- plot_fam_counts(dre, names(de_results)[[i]], n_dots = 20)
}

dotplots[[1]] + 
  ggtitle(titles[[1]]) +
  ggsave(here("results", "PRJNA315294", "figures", "hct116_ko_dox-dotplot.png"),
        width = 8,
        height = 5)
```
