---
title: "PRJNA260377 Analysis"
output:
  html_document:
    df_print: paged
    highlight: tango
    theme: united
    toc: yes
    toc_depth: 4
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

source("helpers/helpers.R")
```

## Read in SummarizedExperiment Object

```{r}
library(tidyverse)
library(here)
library(SummarizedExperiment)


se <- readRDS(here("data", "PRJNA260377", "summarized_experiment.rds"))
```

## Read in gene annotations

```{r}
gtf <- rtracklayer::import("/mnt/data/data_gc/projects/yb5-combined-analysis/doc/gencode.v26.annotation.gtf.gz")
gtf_df <- as.data.frame(gtf)
cds <- subset(gtf_df, 
              type == "gene" & gene_type == "protein_coding", 
              c("gene_id", "gene_name", "seqnames", "start", "end", "width", "strand")
              )
```

## Filter out RNA REs from counts assay

```{r}
se <- subset(se, !str_detect(rownames(se), "tRNA|snRNA|scRNA|rRNA|srpRNA|Simple_repeat|Low_complexity"))
```

## DE pipeline

```{r}
library(edgeR)
library(coriell)


design <- model.matrix(~0 + group, data = colData(se))
colnames(design) <- str_remove(colnames(design), "^group")
y <- DGEList(counts = assay(se, "counts"),
             samples = colData(se))
keep <- filterByExpr(y, design = design)
y <- y[keep,, keep.lib.sizes = FALSE]
y <- calcNormFactors(y, design = design, method = "TMM")
y <- estimateDisp(y, design = design, robust = TRUE)
fit <- glmQLFit(y, design = design, robust = TRUE)
```

## DE testing

```{r}
contrast.matrix <- makeContrasts(
  cmml1_resonder = responder.CMML1 - non_responder.CMML1,
  cmml2_respnder = responder.CMML2 - non_responder.CMML2,
  responder = (responder.CMML1 + responder.CMML2) / 2 - (non_responder.CMML1 + non_responder.CMML2) / 2,
  levels = design
)

# create inputs to map over (titles are same as above)
cons <- colnames(contrast.matrix)
names(cons) <- cons
titles <- c("CMML1 Responder vs Non-Responder", "CMML2 Responder vs Non-Responder", "Responder vs Non-Responder")

# set global significance levels (used in all downstream plots/analyses)
fc <- 1.5
sig <- 0.1

# map over and extract results
de_results <- map2(.x = cons, 
                   .y = titles, 
                   .f = get_de_results, 
                    contrast_matrix = contrast.matrix,
                    fdr = sig,
                    fc = fc,
                    glm_fit = fit)

# extract all results and bind to single df
df <- map(de_results, pluck, "table") %>% bind_rows(.id = "contrast")
```

## Write results out

```{r}
# split DE results into gene and RE results and write out
dge <- df %>% 
  filter(feature_id %in% cds$gene_name) %>% 
  write_tsv(here("results", "PRJNA260377", "data-files", "dge.tsv"))

dre <- df %>% 
  filter(!feature_id %in% cds$gene_name) %>% 
  write_tsv(here("results", "PRJNA260377", "data-files", "dre.tsv"))
```

## Create plots for each contrast 

```{r}
coi <- names(de_results)
gene_vplots <- vector("list", length(coi))
gene_mdplots <- vector("list", length(coi))
re_vplots <- vector("list", length(coi))
re_mdplots <- vector("list", length(coi))

for (i in seq_along(coi)) {
  gene_vplots[[i]] <- 
    dge %>%
    filter(contrast == coi[[i]]) %>% 
    plot_volcano(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
  
  gene_mdplots[[i]] <- 
    dge %>%
    filter(contrast == coi[[i]]) %>% 
    plot_md(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
  
  re_vplots[[i]] <- 
    dre %>% 
    filter(contrast == coi[[i]]) %>% 
    plot_volcano(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
  
  re_mdplots[[i]] <- 
    dre %>% 
    filter(contrast == coi[[i]]) %>% 
    plot_md(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
}
```

## Calculate normalized counts

```{r}
lcpms <- cpm(y, log = TRUE, prior.count = 2)

# split lcpms by gene and by RE
lcpms.gene <- subset(lcpms, rownames(lcpms) %in% cds$gene_name)
lcpms.re <- subset(lcpms, !rownames(lcpms) %in% cds$gene_name)

# Write normalized counts out
write_rds(lcpms.gene, here("results", "PRJNA260377", "rds-files", "gene-lcpms.rds"))
write_rds(lcpms.re, here("results", "PRJNA260377", "rds-files", "re-lcpms.rds"))
```

## PCA

```{r}
library(FactoMineR)
library(factoextra)


# perform PCA with factominer --------------------------------------------------
pca.gene <- PCA(t(lcpms.gene),
                scale.unit = TRUE,
                graph = FALSE,
                ncp = 5)

pca.re <- PCA(t(lcpms.re),
              scale.unit = TRUE,
              graph = FALSE,
              ncp = 5)

# scree plot -------------------------------------------------------------------
fviz_eig(pca.gene, addlabels = TRUE) +
  ggtitle("Protein Coding Genes") +
  ggsave(here("results", "PRJNA260377", "figures", "gene-scree.png"),
         width = 8,
         height = 5)

fviz_eig(pca.re, addlabels = TRUE) +
  ggtitle("Repetitive Elements") +
  ggsave(here("results", "PRJNA260377", "figures", "re-scree.png"),
         width = 8,
         height = 5)

# extract the individual level coordinates -------------------------------------
ind.gene <- get_pca_ind(pca.gene)
ind.re <- get_pca_ind(pca.re)

# plot -------------------------------------------------------------------------
# genes
ind.gene$coord %>% 
  as_tibble(rownames = "sample_name") %>% 
  left_join(as_tibble(colData(se), rownames = "sample_name"), by = "sample_name") %>% 
  ggplot(aes(x = Dim.1, y = Dim.2, color = group)) +
  geom_point(size = 5) +
  geom_hline(yintercept = 0, linetype = 3) +
  geom_vline(xintercept = 0, linetype = 3) +
  labs(title = "Protein Coding Genes",
       x = "PC 1",
       y = "PC 2") +
  scale_color_brewer(palette = "Paired") +
  theme_light() +
  ggsave(here("results", "PRJNA260377", "figures", "gene-pca.png"),
         width = 8,
         height = 5)
# REs
ind.re$coord %>% 
  as_tibble(rownames = "sample_name") %>% 
  left_join(as_tibble(colData(se), rownames = "sample_name"), by = "sample_name") %>% 
  ggplot(aes(x = Dim.1, y = Dim.2, color = group)) +
  geom_point(size = 5) +
  geom_hline(yintercept = 0, linetype = 3) +
  geom_vline(xintercept = 0, linetype = 3) +
  labs(title = "Repetitive Elements",
       x = "PC 1",
       y = "PC 2") +
  scale_color_brewer(palette = "Paired") +
  theme_light() +
  ggsave(here("results", "PRJNA260377", "figures", "re-pca.png"),
         width = 8,
         height = 5)
```

## Heatmaps

```{r}
# create column annotation
col_df <- colData(se)[, c("response_to_decitabine", "chronic_leukemia_type")] %>% 
  as.data.frame()

# create colors for column annotations
rsp_colors <- c("responder" = "firebrick", "non-responder" = "steelblue")
leu_colors <- c("CMML-1" = "#1B9E77", "CMML-2" = "#D95F02")

# put colors in list
ann_colors <- list(response_to_decitabine = rsp_colors, chronic_leukemia_type = leu_colors)

# extract only significant genes and REs ---------------------------------------
sig_genes <- df %>% filter(feature_id %in% cds$gene_name & FDR < sig) %>% pull(feature_id)
sig_res <- df %>% filter(!feature_id %in% cds$gene_name & FDR < sig) %>% pull(feature_id)
lcpms.sig_genes <- subset(lcpms.gene, rownames(lcpms.gene) %in% sig_genes)
lcpms.sig_res <- subset(lcpms.re, rownames(lcpms.re) %in% sig_res)

# plot heatmaps ----------------------------------------------------------------
# NOTHING SIGNIFICANT
# quickmap(lcpms.sig_genes, 
#          annotation_col = col_df,
#          annotation_colors = ann_colors,
#          main = paste("Significant (FDR <", sig, ") Protein Coding Genes"),
#          filename = here("results", "PRJNA260377", "figures", "gene-heatmap.png"))
# 
# quickmap(lcpms.sig_res, 
#          annotation_col = col_df,
#          annotation_colors = ann_colors,
#          main = paste("Significant (FDR <", sig, ") Repetitive Elements"),
#          filename = here("results", "PRJNA260377", "figures", "re-heatmap.png"))
```

## Create Patchwork

```{r}
library(patchwork)


# Genes
(gene_vplots[[1]] | gene_vplots[[2]] | gene_vplots[[3]]) / 
(gene_mdplots[[1]] | gene_mdplots[[2]] | gene_mdplots[[3]] ) +
  plot_annotation("Protein Coding Gene Expression") +
  ggsave(here("results", "PRJNA260377", "figures", "gene-patchwork.png"),
         width = 18,
         height = 10)

# REs
(re_vplots[[1]] | re_vplots[[2]] | re_vplots[[3]]) / 
(re_mdplots[[1]] | re_mdplots[[2]] | re_mdplots[[3]] ) +
  plot_annotation("RE Expression") +
  ggsave(here("results", "PRJNA260377", "figures", "re-patchwork.png"),
         width = 18,
         height = 10)
```
