---
title: "PRJNA391270 Analysis"
output:
  html_document:
    df_print: paged
    highlight: tango
    theme: united
    toc: yes
    toc_depth: 4
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

library(here)
library(tidyverse)
source("helpers/helpers.R")
```

## Read in SummarizedExperiment Object

```{r}
library(SummarizedExperiment)


se <- readRDS(here("data", "PRJNA391270", "summarized_experiment.rds"))
```

## Read in gene annotations

```{r}
cds <- read_rds(here("doc", "gencode.v26.annotation.cds.rds"))
```

## Filter out RNA REs from counts assay

```{r}
se <- subset(se, !str_detect(rownames(se), "tRNA|snRNA|scRNA|rRNA|srpRNA|Simple_repeat|Low_complexity"))
```

## DE pipeline

```{r}
library(edgeR)
library(coriell)


design <- model.matrix(~0 + group, data = colData(se))
colnames(design) <- str_remove(colnames(design), "^group")
y <- DGEList(counts = assay(se, "counts"),
             samples = colData(se))
keep <- filterByExpr(y, design = design)
y <- y[keep,, keep.lib.sizes = FALSE]
y <- calcNormFactors(y, design = design, method = "TMM")
y <- estimateDisp(y, design = design, robust = TRUE)
fit <- glmQLFit(y, design = design, robust = TRUE)
```

## DE testing

```{r}
contrast.matrix <- makeContrasts(
  A498.4GY_vs_A498.Control = A498.4GY_3hr - A498.control,
  A549.4GY_vs_A549.Control = A549.4GY_3hr - A549.control,
  A549.Nutlin_vs_A549.Control = A549.NUT - A549.control,
  A549.TGFB_vs_A549.Control = A549.TGFB - A549.control,
  A549.TGFB_Nutlin_vs_A549.Control = A549.TGFB_NUT - A549.control,
  H460.4GY_vs_H460.Control = H460.4GY_3hr - H460.control,
  HCT116.4GY_vs_HCT116.Control = HCT116.4GY_3hr - HCT116.control,
  LOXIMVI.4GY_vs_LOXIMVI.Control = LOXIMVI.4GY_3hr - LOXIMVI.control,
  MALME3.4GY_vs_MALME3.Control = MALME3.4GY_3hr - MALME3.control,
  MCF7.4GY_vs_MCF7.Control = MCF7.4GY_3hr - MCF7.control,
  SKMEL5.4GY_vs_SKMEL5.Control = SKMEL5.4GY_3hr - SKMEL5.control,
  U2OS.4GY_vs_U2OS.Control = U2OS.4GY_3hr - U2OS.control,
  UACC257.4GY_vs_UACC257.Control = UACC257.4GY_3hr - UACC257.control,
  UO31.4GY_vs_UO31.Control = UO31.4GY_3hr - UO31.control,
  
  x4GY_vs_Control = ((A498.4GY_3hr + 
                      A549.4GY_3hr + 
                      H460.4GY_3hr + 
                      HCT116.4GY_3hr + 
                      LOXIMVI.4GY_3hr +
                      MALME3.4GY_3hr +
                      MCF7.4GY_3hr + 
                      SKMEL5.4GY_3hr +
                      U2OS.4GY_3hr +
                      UACC257.4GY_3hr +
                      UO31.4GY_3hr) / 11) - 
                    ((A498.control +
                      A549.control +
                      H460.control +
                      HCT116.control +
                      LOXIMVI.control +
                      MALME3.control +
                      MCF7.control +
                      SKMEL5.control +
                      U2OS.control +
                      UACC257.control +
                      UO31.control) / 11),
  levels = design
)

# create inputs to map over (titles are same as above)
cons <- colnames(contrast.matrix)
names(cons) <- cons

# set global significance levels (used in all downstream plots/analyses)
fc <- 1.5

# map over and extract results
de_results <- lapply(
  cons, 
  get_de_results2, 
  contrast_matrix = contrast.matrix,
  fc = fc,
  glm_fit = fit
)

# extract all results and bind to single df
df <- lapply(de_results, pluck, "table") %>% bind_rows(.id = "contrast")
```

## Write results out

```{r}
# split DE results into gene and RE results and write out
dge <- df %>% 
  filter(feature_id %in% cds$gene_name) %>% 
  write_tsv(here("results", "PRJNA391270", "data-files", "dge.tsv"))

dre <- df %>% 
  filter(!feature_id %in% cds$gene_name) %>% 
  write_tsv(here("results", "PRJNA391270", "data-files", "dre.tsv"))
```

## Calculate normalized counts

```{r}
lcpms <- cpm(y, log = TRUE, prior.count = 2)

# split lcpms by gene and by RE
lcpms.gene <- subset(lcpms, rownames(lcpms) %in% cds$gene_name)
lcpms.re <- subset(lcpms, !rownames(lcpms) %in% cds$gene_name)

# Write normalized counts out
write_rds(lcpms.gene, here("results", "PRJNA391270", "rds-files", "gene-lcpms.rds"))
write_rds(lcpms.re, here("results", "PRJNA391270", "rds-files", "re-lcpms.rds"))
```

---

# OLD CODE

## Create plots for each contrast 

```{r eval=FALSE, include=FALSE}
coi <- names(de_results)
gene_vplots <- vector("list", length(coi))
gene_mdplots <- vector("list", length(coi))
re_vplots <- vector("list", length(coi))
re_mdplots <- vector("list", length(coi))

for (i in seq_along(coi)) {
  gene_vplots[[i]] <- 
    dge %>%
    filter(contrast == coi[[i]]) %>% 
    plot_volcano(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
  
  gene_mdplots[[i]] <- 
    dge %>%
    filter(contrast == coi[[i]]) %>% 
    plot_md(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
  
  re_vplots[[i]] <- 
    dre %>% 
    filter(contrast == coi[[i]]) %>% 
    plot_volcano(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
  
  re_mdplots[[i]] <- 
    dre %>% 
    filter(contrast == coi[[i]]) %>% 
    plot_md(fdr = sig, lfc = log2(fc)) +
    ggtitle(titles[[i]])
}
```

## PCA

```{r eval=FALSE, include=FALSE}
library(FactoMineR)
library(factoextra)


# perform PCA with factominer --------------------------------------------------
pca.gene <- PCA(t(lcpms.gene),
                scale.unit = TRUE,
                graph = FALSE,
                ncp = 5)

pca.re <- PCA(t(lcpms.re),
              scale.unit = TRUE,
              graph = FALSE,
              ncp = 5)

# scree plot -------------------------------------------------------------------
fviz_eig(pca.gene, addlabels = TRUE) +
  ggtitle("Protein Coding Genes") +
  ggsave(here("results", "PRJNA391270", "figures", "gene-scree.png"),
         width = 8,
         height = 5)

fviz_eig(pca.re, addlabels = TRUE) +
  ggtitle("Repetitive Elements") +
  ggsave(here("results", "PRJNA391270", "figures", "re-scree.png"),
         width = 8,
         height = 5)

# extract the individual level coordinates -------------------------------------
ind.gene <- get_pca_ind(pca.gene)
ind.re <- get_pca_ind(pca.re)

# plot -------------------------------------------------------------------------
# genes
ind.gene$coord %>% 
  as_tibble(rownames = "sample_name") %>% 
  left_join(as_tibble(colData(se), rownames = "sample_name"), by = "sample_name") %>% 
  separate(group, into = c("cell_type", "drug"), sep = "\\.") %>% 
  ggplot(aes(x = Dim.1, y = Dim.2, color = cell_type, shape = drug)) +
  geom_point(size = 5) +
  geom_hline(yintercept = 0, linetype = 3) +
  geom_vline(xintercept = 0, linetype = 3) +
  labs(title = "Protein Coding Genes",
       x = "PC 1",
       y = "PC 2") +
  scale_color_brewer(palette = "Set3") +
  theme_light() +
  ggsave(here("results", "PRJNA391270", "figures", "gene-pca.png"),
         width = 8,
         height = 5)
# REs
ind.re$coord %>% 
  as_tibble(rownames = "sample_name") %>% 
  left_join(as_tibble(colData(se), rownames = "sample_name"), by = "sample_name") %>% 
  separate(group, into = c("cell_type", "drug"), sep = "\\.") %>% 
  ggplot(aes(x = Dim.1, y = Dim.2, color = cell_type, shape = drug)) +
  geom_point(size = 5) +
  geom_hline(yintercept = 0, linetype = 3) +
  geom_vline(xintercept = 0, linetype = 3) +
  labs(title = "Repetitive Elements",
       x = "PC 1",
       y = "PC 2") +
  scale_color_brewer(palette = "Set3") +
  theme_light() +
  ggsave(here("results", "PRJNA391270", "figures", "re-pca.png"),
         width = 8,
         height = 5)
```

## Heatmaps

```{r eval=FALSE, include=FALSE}
# create column annotation
col_df <- colData(se)[, c("group"), drop = FALSE] %>%
  as.data.frame() %>% 
  separate(group, into = c("cell_type", "drug"), sep = "\\.") %>% 
  mutate(cell_type = factor(cell_type),
         drug = factor(drug))

# create colors for column annotations
cell_colors <- RColorBrewer::brewer.pal(n = nlevels(col_df$cell_type), "Set3")
drug_colors <- RColorBrewer::brewer.pal(n = nlevels(col_df$drug), "Set1")
names(cell_colors) <- levels(col_df$cell_type)
names(drug_colors) <- levels(col_df$drug)

# put colors in list
ann_colors <- list(cell_type = cell_colors, drug = drug_colors)

# extract only significant genes and REs ---------------------------------------
sig_genes <- df %>% filter(feature_id %in% cds$gene_name & FDR < sig) %>% pull(feature_id)
sig_res <- df %>% filter(!feature_id %in% cds$gene_name & FDR < sig) %>% pull(feature_id)
lcpms.sig_genes <- subset(lcpms.gene, rownames(lcpms.gene) %in% sig_genes)
lcpms.sig_res <- subset(lcpms.re, rownames(lcpms.re) %in% sig_res)

# plot heatmaps ----------------------------------------------------------------
quickmap(lcpms.sig_genes, 
         annotation_col = col_df,
         annotation_colors = ann_colors,
         main = paste("Significant (FDR <", sig, ") Protein Coding Genes"),
         filename = here("results", "PRJNA391270", "figures", "gene-heatmap.png"))

quickmap(lcpms.sig_res, 
         annotation_col = col_df,
         annotation_colors = ann_colors,
         main = paste("Significant (FDR <", sig, ") Repetitive Elements"),
         filename = here("results", "PRJNA391270", "figures", "re-heatmap.png"))
```

## Create Patchworks

```{r eval=FALSE, include=FALSE}
library(patchwork)


# Gene (part 1)
(gene_vplots[[1]] + scale_y_continuous(limits = c(0, 6)) + scale_x_continuous(limits = c(-10, 10)) |
 gene_vplots[[2]] + scale_y_continuous(limits = c(0, 6)) + scale_x_continuous(limits = c(-10, 10)) |
 gene_vplots[[3]] + scale_y_continuous(limits = c(0, 6)) + scale_x_continuous(limits = c(-10, 10)) ) /
(gene_vplots[[4]] + scale_y_continuous(limits = c(0, 6)) + scale_x_continuous(limits = c(-10, 10)) |
 gene_vplots[[5]] + scale_y_continuous(limits = c(0, 6)) + scale_x_continuous(limits = c(-10, 10)) |
 gene_vplots[[6]] + scale_y_continuous(limits = c(0, 6)) + scale_x_continuous(limits = c(-10, 10))) +
plot_annotation("Protein Coding Gene Expression") +
plot_layout(guides = "collect") +
ggsave(here("results", "PRJNA391270", "figures", "gene-vplots-1.png"),
       width = 18, 
       height = 10)

# part 2
(gene_vplots[[7]] |
 gene_vplots[[8]] |
 gene_vplots[[9]] ) /
(gene_vplots[[10]] |
 gene_vplots[[11]] |
 gene_vplots[[12]]) +
plot_annotation("Protein Coding Gene Expression") +
plot_layout(guides = "collect") +
ggsave(here("results", "PRJNA391270", "figures", "gene-vplots-2.png"),
       width = 18, 
       height = 10)

# part 3
(gene_vplots[[13]] |
 gene_vplots[[14]] ) +
plot_annotation("Protein Coding Gene Expression") +
plot_layout(guides = "collect") +
ggsave(here("results", "PRJNA391270", "figures", "gene-vplots-3.png"),
       width = 18, 
       height = 10)

# Gene md (part 1)
(gene_mdplots[[1]] + scale_y_continuous(limits = c(-10, 10)) |
 gene_mdplots[[2]] + scale_y_continuous(limits = c(-10, 10)) |
 gene_mdplots[[3]] + scale_y_continuous(limits = c(-10, 10)) ) /
(gene_mdplots[[4]] + scale_y_continuous(limits = c(-10, 10)) |
 gene_mdplots[[5]] + scale_y_continuous(limits = c(-10, 10)) |
 gene_mdplots[[6]] + scale_y_continuous(limits = c(-10, 10))) +
plot_annotation("Protein Coding Gene Expression") +
plot_layout(guides = "collect") +
ggsave(here("results", "PRJNA391270", "figures", "gene-mdplots-1.png"),
       width = 18, 
       height = 10)

# part 2
(gene_mdplots[[7]] |
 gene_mdplots[[8]] |
 gene_mdplots[[9]] ) /
(gene_mdplots[[10]] |
 gene_mdplots[[11]] |
 gene_mdplots[[12]]) +
plot_annotation("Protein Coding Gene Expression") +
plot_layout(guides = "collect") +
ggsave(here("results", "PRJNA391270", "figures", "gene-mdplots-2.png"),
       width = 18, 
       height = 10)

# part 3
(gene_mdplots[[13]] |
 gene_mdplots[[14]] ) +
plot_annotation("Protein Coding Gene Expression") +
plot_layout(guides = "collect") +
ggsave(here("results", "PRJNA391270", "figures", "gene-mdplots-3.png"),
       width = 18, 
       height = 10)

# RE ---------------------------------------------------------------------------
(re_vplots[[1]] + scale_y_continuous(limits = c(0, 3)) + scale_x_continuous(limits = c(-10, 10)) |
 re_vplots[[2]] + scale_y_continuous(limits = c(0, 3)) + scale_x_continuous(limits = c(-10, 10)) |
 re_vplots[[3]] + scale_y_continuous(limits = c(0, 3)) + scale_x_continuous(limits = c(-10, 10)) ) /
(re_vplots[[4]] + scale_y_continuous(limits = c(0, 3)) + scale_x_continuous(limits = c(-10, 10)) |
 re_vplots[[5]] + scale_y_continuous(limits = c(0, 3)) + scale_x_continuous(limits = c(-10, 10)) |
 re_vplots[[6]] + scale_y_continuous(limits = c(0, 3)) + scale_x_continuous(limits = c(-10, 10))) +
plot_annotation("RE Expression") +
plot_layout(guides = "collect") +
ggsave(here("results", "PRJNA391270", "figures", "re-vplots-1.png"),
       width = 18, 
       height = 10)

# part 2
(re_vplots[[7]] |
 re_vplots[[8]] |
 re_vplots[[9]] ) /
(re_vplots[[10]] |
 re_vplots[[11]] |
 re_vplots[[12]]) +
plot_annotation("RE Expression") +
plot_layout(guides = "collect") +
ggsave(here("results", "PRJNA391270", "figures", "re-vplots-2.png"),
       width = 18, 
       height = 10)

# part 3
(re_vplots[[13]] |
 re_vplots[[14]] ) +
plot_annotation("RE Expression") +
plot_layout(guides = "collect") +
ggsave(here("results", "PRJNA391270", "figures", "re-vplots-3.png"),
       width = 18, 
       height = 10)

# RE md plots (part 1)
(re_mdplots[[1]] + scale_y_continuous(limits = c(-10, 10)) |
 re_mdplots[[2]] + scale_y_continuous(limits = c(-10, 10)) |
 re_mdplots[[3]] + scale_y_continuous(limits = c(-10, 10)) ) /
(re_mdplots[[4]] + scale_y_continuous(limits = c(-10, 10)) |
 re_mdplots[[5]] + scale_y_continuous(limits = c(-10, 10)) |
 re_mdplots[[6]] + scale_y_continuous(limits = c(-10, 10))) +
plot_annotation("RE Expression") +
plot_layout(guides = "collect") +
ggsave(here("results", "PRJNA391270", "figures", "re-mdplots-1.png"),
       width = 18, 
       height = 10)

# part 2
(re_mdplots[[7]] |
 re_mdplots[[8]] |
 re_mdplots[[9]] ) /
(re_mdplots[[10]] |
 re_mdplots[[11]] |
 re_mdplots[[12]]) +
plot_annotation("RE Expression") +
plot_layout(guides = "collect") +
ggsave(here("results", "PRJNA391270", "figures", "re-mdplots-2.png"),
       width = 18, 
       height = 10)

# part 3
(re_mdplots[[13]] |
 re_mdplots[[14]] ) +
plot_annotation("RE Expression") +
plot_layout(guides = "collect") +
ggsave(here("results", "PRJNA391270", "figures", "re-mdplots-3.png"),
       width = 18, 
       height = 10)
```

## Create Family-Level Dotplots for significant REs

```{r eval=FALSE, include=FALSE}
dotplots <- vector("list", length(names(de_results)))
for (i in seq_along(names(de_results))) {
  dotplots[[i]] <- plot_fam_counts(dre, names(de_results)[[i]], n_dots = 20)
}

# remove null dotplots
dotplots <- dotplots[!sapply(dotplots, is.null)]

(dotplots[[1]] |
 dotplots[[2]] ) /
(dotplots[[3]] |
 dotplots[[4]] ) +
plot_annotation("RE Family Expression") +
ggsave(here("results", "PRJNA391270", "figures", "dotplots.png"),
       width = 18,
       height = 7)
```
