---
title: "Tak Clean Contrasts"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in original DE files

renamed to '...original.tsv'

```{r}
library(data.table)
library(here)


dge <- fread(here("results", "tak", "data-files", "dge.original.tsv"))
dre <- fread(here("results", "tak", "data-files", "dre.original.tsv"))
```

## Rename contrasts

```{r}
dge[, contrast := fcase(
  contrast == "dac_depsi", "Decitabine_Depsipeptide_vs_DMSO",
  contrast == "dac_gsk343", "Decitabine_GSK343_vs_DMSO",
  contrast == "dac_s2102", "Decitabine_S2102_vs_DMSO",
  contrast == "dac_unc0628", "Decitabine_UNC0628_vs_DMSO",
  contrast == "dac", "Decitabine_vs_DMSO",
  contrast == "depsi", "Depsipeptide_vs_DMSO",
  contrast == "gsk343", "GSK343_vs_DMSO",
  contrast == "s2102", "S2102_vs_DMSO",
  contrast == "unc0628", "UNC0628_vs_DMSO",
  default = "UNKNOWN")]

dre[, contrast := fcase(
  contrast == "dac_depsi", "Decitabine_Depsipeptide_vs_DMSO",
  contrast == "dac_gsk343", "Decitabine_GSK343_vs_DMSO",
  contrast == "dac_s2102", "Decitabine_S2102_vs_DMSO",
  contrast == "dac_unc0628", "Decitabine_UNC0628_vs_DMSO",
  contrast == "dac", "Decitabine_vs_DMSO",
  contrast == "depsi", "Depsipeptide_vs_DMSO",
  contrast == "gsk343", "GSK343_vs_DMSO",
  contrast == "s2102", "S2102_vs_DMSO",
  contrast == "unc0628", "UNC0628_vs_DMSO",
  default = "UNKNOWN")]
```

## Write out

```{r}
fwrite(dge, here("results", "tak", "data-files", "dge.tsv"), sep = "\t")
fwrite(dre, here("results", "tak", "data-files", "dre.tsv"), sep = "\t")
```

