---
title: "Toyo Clean Contrasts"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in original DE files

renamed to '...original.tsv'

```{r}
library(data.table)
library(here)


dge <- fread(here("results", "toyo", "data-files", "dge.original.tsv"))
dre <- fread(here("results", "toyo", "data-files", "dre.original.tsv"))
```

## Rename contrasts

```{r}
dge[, contrast := fcase(
  contrast == "toyo_2hr", "Toyocamycin_vs_DMSO_2hr",
  contrast == "toyo_10hr", "Toyocamycin_vs_DMSO_10hr",
  contrast == "toyo_24hr", "Toyocamycin_vs_DMSO_24hr",
  contrast == "toyo_48hr", "Toyocamycin_vs_DMSO_48hr",
  contrast == "toyo_72hr", "Toyocamycin_vs_DMSO_72hr",
  default = "UNKNOWN")]

dre[, contrast := fcase(
  contrast == "toyo_2hr", "Toyocamycin_vs_DMSO_2hr",
  contrast == "toyo_10hr", "Toyocamycin_vs_DMSO_10hr",
  contrast == "toyo_24hr", "Toyocamycin_vs_DMSO_24hr",
  contrast == "toyo_48hr", "Toyocamycin_vs_DMSO_48hr",
  contrast == "toyo_72hr", "Toyocamycin_vs_DMSO_72hr",
  default = "UNKNOWN")]
```

## Write out

```{r}
fwrite(dge, here("results", "toyo", "data-files", "dge.tsv"), sep = "\t")
fwrite(dre, here("results", "toyo", "data-files", "dre.tsv"), sep = "\t")
```

